DROP TABLE ORASSADM.OPF_USER CASCADE CONSTRAINTS;

CREATE TABLE ORASSADM.OPF_USER
(
  IDENPOST  NUMBER(10)                          NOT NULL,
  NOM_UTIL  VARCHAR2(30 BYTE)                   NOT NULL,
  NOM_PREN  VARCHAR2(100 BYTE),
  TELEUSER  VARCHAR2(20 BYTE),
  MAILUSER  VARCHAR2(100 BYTE),
  CODEFONC  NUMBER(5),
  ADREUSER  VARCHAR2(100 BYTE),
  CODESOCI  NUMBER(2),
  FLAGADMI  VARCHAR2(1 BYTE),
  CODEBENE  NUMBER(5),
  FLAGTRAC  VARCHAR2(1 BYTE)                    DEFAULT 'N',
  TYPPROPR  VARCHAR2(10 BYTE),
  CODEASSU  NUMBER(12),
  ID_CARTE  NUMBER(25),
  STATUSER  VARCHAR2(1 BYTE)                    DEFAULT 'A'                   NOT NULL,
  DATESTAT  DATE                                DEFAULT sysdate               NOT NULL,
  EXPI__LE  DATE,
  MODI_PAR  VARCHAR2(60 BYTE),
  MODI__LE  DATE,
  CREE_PAR  VARCHAR2(60 BYTE),
  CREE__LE  DATE,
  USERPASS  VARCHAR2(200 BYTE),
  SALTPASS  VARCHAR2(600 BYTE),
  ENTIGEST  NUMBER(10),
  MUSCHAPW  VARCHAR2(1 BYTE)                    DEFAULT 'N',
  DATCHAPW  DATE,
  NUMEIMMA  VARCHAR2(50 BYTE),
  IDENPHOT  NUMBER(20),
  LOG_LEVL  VARCHAR2(1 BYTE)                    DEFAULT 'E',
  CODEAPPO  NUMBER(10)
)
TABLESPACE ORASS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;

COMMENT ON COLUMN ORASSADM.OPF_USER.TYPPROPR IS 'Type Profil principal';

COMMENT ON COLUMN ORASSADM.OPF_USER.MUSCHAPW IS 'Si "O" force de changement du mot de passe';

COMMENT ON COLUMN ORASSADM.OPF_USER.DATCHAPW IS 'Dernier date de changement du mot de passe';

COMMENT ON COLUMN ORASSADM.OPF_USER.LOG_LEVL IS 'Niveau des logs: D: Debug, I: Info, W: Warning, E: Error';

COMMENT ON COLUMN ORASSADM.OPF_USER.CODEAPPO IS 'Code Apporteur connecté';


CREATE UNIQUE INDEX ORASSADM.CLE_ORASS_USER ON ORASSADM.OPF_USER
(NOM_UTIL)
LOGGING
TABLESPACE ORASS_IX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
CREATE UNIQUE INDEX ORASSADM.PK_ORASS_USER ON ORASSADM.OPF_USER
(IDENPOST)
LOGGING
TABLESPACE ORASS_IX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE ORASSADM.OPF_USER ADD (
  CONSTRAINT PK_ORASS_USER
  PRIMARY KEY
  (IDENPOST)
  USING INDEX ORASSADM.PK_ORASS_USER
  ENABLE VALIDATE);


CREATE INDEX ORASSADM.FK_USER_CODEFONC ON ORASSADM.OPF_USER
(CODEFONC)
LOGGING
TABLESPACE ORASS_IX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX ORASSADM.IFK_USER_STATUSER ON ORASSADM.OPF_USER
(STATUSER)
LOGGING
TABLESPACE ORASS_IX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX ORASSADM.IFK_USER_TYPPROPR ON ORASSADM.OPF_USER
(TYPPROPR)
LOGGING
TABLESPACE ORASS_IX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX ORASSADM.IFK_USR_ENT_GEST ON ORASSADM.OPF_USER
(ENTIGEST)
LOGGING
TABLESPACE ORASS_IX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE PUBLIC SYNONYM OPF_USER FOR ORASSADM.OPF_USER;


ALTER TABLE ORASSADM.OPF_USER ADD (
  CONSTRAINT FK_USER_CODEFONC 
  FOREIGN KEY (CODEFONC) 
  REFERENCES ORASSADM.OPF_USER_FONCTION (CODEFONC)
  ENABLE VALIDATE
,  CONSTRAINT FK_USER_STATUSER 
  FOREIGN KEY (STATUSER) 
  REFERENCES ORASSADM.OPF_STATUS_USER (STATUSER)
  ENABLE VALIDATE
,  CONSTRAINT FK_USER_TYPPROPR 
  FOREIGN KEY (TYPPROPR) 
  REFERENCES ORASSADM.OPF_TYPE_PROFIL (CODTYPPR)
  ENABLE VALIDATE
,  CONSTRAINT FK_USR_ENT_GEST 
  FOREIGN KEY (ENTIGEST) 
  REFERENCES ORASSADM.ENTITE_GESTION (ENTIGEST)
  ENABLE VALIDATE);

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON ORASSADM.OPF_USER TO PUBLIC;
